[package]
name = "esp32c3-idf-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.7"
esp-idf-hal = "0.35.2"
esp-idf-sys = { version = "0.31.0", features = ["binstart"] }

[build-dependencies]
embuild = "0.28"
anyhow = "1"